def PATH = '/home/mp_task/HelloWorld_MPtask/nodejs'
pipeline {
        agent any
        triggers {pollSCM ''}
        stages {
                stage ('clone'){
                steps () {
                        sh """
                        # checkout scm
                        git url : 'https://github.com/GNMegha/HelloWorld_MPtask.git'
                        """
                        }
                     }
                stage ('build'){
                steps {
                        sh """
                            cd $PATH
                            docker build -t Dockerfile .
                           """
                       }
                    }

                }
}
}
